Feat/resolve tfsec
mentoriaiac/iac-modulo-s3 pull request #10
Opened 2022-05-04 23:45 UTC by williamsanmartin4

# Titulo

Resolve issues referente ao tfsec

- [x] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x] Dê um titulo que expresse o objetivo do PR
- [x] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [x] Descreva o objetivo do PR
- [x] Inclua links relevantes para a sua modificação/sugestão/correção
- [x] Descreva um passo-a-passo para testar o seu PR

## Issue

https://github.com/mentoriaiac/iac-modulo-s3/issues/9
https://github.com/mentoriaiac/iac-modulo-s3/issues/8
https://github.com/mentoriaiac/iac-modulo-s3/issues/7
https://github.com/mentoriaiac/iac-modulo-s3/issues/6

## Objetivo

Resolve issues referente ao tfsec

## Referências
https://aquasecurity.github.io/tfsec/latest/checks/aws/s3/specify-public-access-block
https://aquasecurity.github.io/tfsec/latest/checks/aws/s3/enable-versioning
https://aquasecurity.github.io/tfsec/latest/checks/aws/s3/enable-bucket-logging
https://aquasecurity.github.io/tfsec/latest/checks/aws/s3/enable-bucket-encryption

## Como testar
## Como utilizar o módulo

No diretório [_examples/_](examples/) podem ser encontrados exemplos de utilização, incluindo instruções de como executá-los.

Mas para adiantar um exemplo simples, a utilização do módulo pode ser feita da seguinte maneira:

- Criação de um bucket com ACL _private_

```hcl
module "s3_bucket" {
  source      = "github.com/marcelomansur/iac-modulo-s3"
  bucket_name = "my-private-bucket"
}
```

2022-05-08 16:46 UTC, gomex requested changes
Ta muito bom, mas faltam alguns pequenos detalhes ;)

2022-05-08 16:46 UTC, gomex commented on main.tf
> +    status = "Enabled"
Poderia colocar isso como variável? pode até colocar o "Enabled" como default, mas seria legal ser variável.

2022-05-08 16:46 UTC, gomex commented on main.tf
> +  target_prefix = "log/"
Poderia colocar isso como variável? pode até colocar o "log/" como default, mas seria legal ser variável.

2022-05-08 16:46 UTC, gomex commented on examples/public-bucket/main.tf
> +  bucket_name = "public-bucket-example222"
Pode retornar o valor antigo? ;)

2022-05-08 16:46 UTC, gomex commented on examples/private-bucket/main.tf
> +  bucket_name = "iac-williammartin-teste"
Pode retornar o valor antigo? ;)

2022-05-15 16:04 UTC, gomex commented
@william-sanmartin eu percebi que sua mudança resolve os problemas, mas o tfsec ainda pega os problemas, pois você resolveu com outros resources, ao invés de colocar opções dentro do resource do bucket, que é a melhor opção, em minha opinião, claro.

Nesse caso, a curto prazo, só no resta ignorar esses alertas: https://aquasecurity.github.io/tfsec/v0.61.3/getting-started/configuration/ignores/

Poderia colocar isso pra fazer o pipeline parar de quebrar?

2022-05-22 15:37 UTC, EzzioWMoreira commented
@williamsanmartin4 Tá muito bom. Só uma duvida. Você chegou a rodar o terraform fmt para identar o código?

2022-05-22 15:37 UTC, gomex approved these changes

2022-05-22 15:38 UTC, merged